# Generated by Django 4.1.10 on 2023-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="new_stock",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
