# Generated by Django 4.2.7 on 2023-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_new_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_take_done',
            field=models.BooleanField(default=False),
        ),
    ]
