# Generated by Django 5.0.4 on 2024-04-28 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_products_stock_take_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="user",
        ),
    ]
