# Generated by Django 5.0.4 on 2024-05-10 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_sales_date_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="date_sold",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
