# Generated by Django 5.0.4 on 2024-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "income_balance",
                    models.CharField(
                        choices=[
                            ("Income Statement", "Income Statement"),
                            ("Balance sheet", "Balance Sheet"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "account_category",
                    models.CharField(
                        choices=[
                            ("Assest", "Assest"),
                            ("Liability", "Liability"),
                            ("Equity", "Equity"),
                            ("Income", "Income"),
                            ("Expense", "Expense"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GLAccountCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "account_category",
                    models.CharField(
                        choices=[
                            ("Assest", "Assest"),
                            ("Liability", "Liability"),
                            ("Equity", "Equity"),
                            ("Income", "Income"),
                            ("Expense", "Expense"),
                        ],
                        max_length=255,
                    ),
                ),
                ("balance", models.IntegerField()),
            ],
            options={
                "verbose_name": "G/L Account Category",
                "verbose_name_plural": "G/L Account Categories",
            },
        ),
    ]
